# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-24 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
