# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_auto_20161124_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='url',
            field=models.CharField(default='/', max_length=64, unique=True),
            preserve_default=False,
        ),
    ]
