# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-26 18:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_game_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='score',
            old_name='score',
            new_name='value',
        ),
    ]
